import os
import uuid
import random
from flask import Flask, request, jsonify, render_template
from openai import OpenAI

app = Flask(__name__)

# ============================================================
# OPENROUTER
# ============================================================

API_KEY = os.environ.get("OPENROUTER_API_KEY")
MODEL = os.environ.get("OPENROUTER_MODEL", "openai/gpt-oss-20b")

client = None

if API_KEY:
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=API_KEY
    )

# ============================================================
# WORLD / STORY STORAGE
# ============================================================

worlds = {}

ENDING_TYPES = [
    "hopeful",
    "tragic",
    "mysterious",
    "rebellion",
    "peaceful",
    "bittersweet",
    "unknown"
]


def new_world():
    world_id = str(uuid.uuid4())

    world = {
        "id": world_id,
        "name": random.choice([
            "Echoes of Tomorrow",
            "The Last Bell",
            "Shadows of Choice",
            "A World Between",
            "The Unwritten Day",
            "Fragments",
            "After the Signal"
        ]),
        "turn": 0,
        "location": "Classroom",
        "memories": [],
        "characters": {},
        "choices": [],
        "story_nodes": {},
        "current_node": "start",
        "ending": None,
        "finished": False,
        "visited_nodes": [],
        "created": True
    }

    worlds[world_id] = world
    return world


# ============================================================
# STORY TREE
# ============================================================

def build_story_tree(world):
    """
    Creates a unique branching structure for every world.

    The exact story is generated by the AI, but the server keeps
    track of every node the player visits.
    """

    if world["story_nodes"]:
        return

    first_names = [
        "Alex", "Jordan", "Maya", "Eli",
        "Sam", "Riley", "Noah", "Taylor"
    ]

    world["characters"] = {
        "main_character": random.choice(first_names),
        "friend": random.choice(first_names),
        "mysterious_character": random.choice(first_names)
    }

    world["story_nodes"]["start"] = {
        "title": "The Beginning",
        "parent": None,
        "choices": [],
        "status": "current"
    }


def make_story_prompt(world, player_message):
    history = world["memories"][-20:]

    character = world["characters"].get("main_character", "the main character")
    friend = world["characters"].get("friend", "their friend")
    mysterious = world["characters"].get(
        "mysterious_character",
        "the mysterious person"
    )

    return f"""
You are the story engine for a long-running interactive game.

The game is a branching story inspired by cinematic choice-based
games. Every player decision must have consequences later.

IMPORTANT:
- Never reset the story unless the user explicitly creates/resets a world.
- Remember previous choices.
- Characters remember important events.
- Characters should react naturally to the player's actions.
- Do not simply repeat the player's instructions.
- If the player says they travel somewhere, describe the travel and
  have characters react naturally instead of treating the travel
  instruction as dialogue.
- The player controls their own character.
- NPCs control themselves.
- NPCs may disagree with the player.
- NPCs may misunderstand things.
- NPC relationships can change.
- Earlier choices should affect later dialogue and events.
- Do not make every choice obviously good or bad.
- Some consequences should happen much later.
- Do not force an ending too quickly.
- Keep the story cinematic and detailed.
- Write several paragraphs when appropriate.
- Give meaningful choices at the end.
- Choices should be different enough that they lead to different
  future events.
- The story should be capable of reaching at least five major endings.

MAIN CHARACTER:
{character}

FRIEND:
{friend}

MYSTERIOUS CHARACTER:
{mysterious}

CURRENT LOCATION:
{world["location"]}

TURN:
{world["turn"]}

PREVIOUS CHOICES:
{world["choices"][-15:]}

IMPORTANT MEMORIES:
{history}

CURRENT PLAYER ACTION:
{player_message}

Return JSON with EXACTLY these fields:

{{
  "story": "the next section of the story",
  "location": "current location",
  "choices": [
      "choice 1",
      "choice 2",
      "choice 3"
  ],
  "new_memory": "one important event to remember",
  "node_title": "short title for this story node",
  "ending": null
}}

If the story genuinely reaches an ending, "ending" must contain
one of:

hopeful
tragic
mysterious
rebellion
peaceful
bittersweet
unknown

Otherwise ending must be null.
"""


def ask_ai(world, player_message):
    if not client:
        raise RuntimeError(
            "OPENROUTER_API_KEY is missing. Add it to Render Environment Variables."
        )

    prompt = make_story_prompt(world, player_message)

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a branching interactive story engine. "
                    "Return valid JSON only."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.9,
        max_tokens=1800
    )

    text = response.choices[0].message.content.strip()

    # Remove accidental markdown fences
    if text.startswith("```"):
        lines = text.splitlines()

        if lines and lines[0].startswith("```"):
            lines = lines[1:]

        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        text = "\n".join(lines).strip()

    import json

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Fallback if model didn't return perfect JSON
        return {
            "story": text,
            "location": world["location"],
            "choices": [
                "Continue",
                "Investigate",
                "Ask someone what is happening"
            ],
            "new_memory": player_message,
            "node_title": "A New Moment",
            "ending": None
        }


# ============================================================
# HOME
# ============================================================

@app.route("/")
def home():
    return render_template("index.html")


# ============================================================
# CREATE WORLD
# ============================================================

@app.route("/world/new", methods=["POST"])
def create_world():
    world = new_world()
    build_story_tree(world)

    return jsonify({
        "success": True,
        "world": world
    })


# ============================================================
# GET WORLD
# ============================================================

@app.route("/world/<world_id>", methods=["GET"])
def get_world(world_id):
    world = worlds.get(world_id)

    if not world:
        return jsonify({
            "error": "World not found"
        }), 404

    return jsonify({
        "success": True,
        "world": world
    })


# ============================================================
# RESET WORLD
# ============================================================

@app.route("/world/<world_id>/reset", methods=["POST"])
def reset_world(world_id):
    if world_id in worlds:
        del worlds[world_id]

    world = new_world()
    build_story_tree(world)

    return jsonify({
        "success": True,
        "world": world
    })


# ============================================================
# CHAT / STORY
# ============================================================

@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json(silent=True) or {}

    world_id = data.get("world_id")
    message = data.get("message", "").strip()

    if not world_id:
        return jsonify({
            "error": "No world selected."
        }), 400

    if not message:
        return jsonify({
            "error": "Message cannot be empty."
        }), 400

    world = worlds.get(world_id)

    if not world:
        return jsonify({
            "error": "World not found."
        }), 404

    if world["finished"]:
        return jsonify({
            "error": "This world has already ended.",
            "world": world
        }), 400

    try:
        result = ask_ai(world, message)

        world["turn"] += 1

        world["location"] = result.get(
            "location",
            world["location"]
        )

        world["choices"].append(message)

        memory = result.get("new_memory")

        if memory:
            world["memories"].append(memory)

        node_id = str(uuid.uuid4())[:8]

        parent = world["current_node"]

        node_title = result.get(
            "node_title",
            f"Chapter {world['turn']}"
        )

        world["story_nodes"][node_id] = {
            "title": node_title,
            "parent": parent,
            "choice": message,
            "turn": world["turn"],
            "location": world["location"],
            "status": "visited",
            "choices": result.get("choices", [])
        }

        world["current_node"] = node_id
        world["visited_nodes"].append(node_id)

        ending = result.get("ending")

        if ending in ENDING_TYPES:
            world["ending"] = ending
            world["finished"] = True

        return jsonify({
            "success": True,
            "story": result.get("story", ""),
            "choices": result.get("choices", []),
            "location": world["location"],
            "ending": world["ending"],
            "world": world
        })

    except Exception as e:
        return jsonify({
            "error": str(e)
        }), 500


# ============================================================
# STORY TREE
# ============================================================

@app.route("/world/<world_id>/tree", methods=["GET"])
def story_tree(world_id):
    world = worlds.get(world_id)

    if not world:
        return jsonify({
            "error": "World not found."
        }), 404

    return jsonify({
        "success": True,
        "tree": world["story_nodes"],
        "current_node": world["current_node"],
        "visited": world["visited_nodes"],
        "ending": world["ending"]
    })


# ============================================================
# REPLAY
# ============================================================

@app.route("/world/<world_id>/replay", methods=["POST"])
def replay_world(world_id):
    old_world = worlds.get(world_id)

    if not old_world:
        return jsonify({
            "error": "World not found."
        }), 404

    # Create a fresh version of the same world concept.
    world = new_world()

    world["name"] = old_world["name"] + " — Replay"

    build_story_tree(world)

    return jsonify({
        "success": True,
        "world": world
    })


# ============================================================
# HEALTH CHECK
# ============================================================

@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "status": "online",
        "openrouter": bool(API_KEY),
        "model": MODEL
    })


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(
        host="0.0.0.0",
        port=port,
        debug=False
    )
